paths:
  rgb_f: '/mnt/data01/PPOSS Home of the future data collection/Sensor Node 6 (HAR6)/2025_04_22_15_10_07_SB-29937C/rgb.avi'  
  rgb_ts_f_txt: '/mnt/data01/PPOSS Home of the future data collection/Sensor Node 6 (HAR6)/2025_04_22_15_10_07_SB-29937C/rgb_ts.txt'
  rgb_F: "/mnt/data01/DepthPro/Sensor Node 6 (HAR6)/2025_04_22_15_10_07_SB-29937C/woseg/rgb_png"
  depth_F_png: "/mnt/data01/DepthPro/Sensor Node 6 (HAR6)/2025_04_22_15_10_07_SB-29937C/woseg/depth_d_png"
  depth_F_npy: "/mnt/data01/DepthPro/Sensor Node 6 (HAR6)/2025_04_22_15_10_07_SB-29937C/woseg/depth_d_npy"
  seg_f_txt: "/mnt/data01/PPOSS Home of the future data collection/Segmentations/2025-04-22-15-01-54_SB-29937C.txt"

actions:
  total_amount: 38

HAR6:
  visible_s: [0,5,6,7,12,20,35,37]